import React, { useState } from "react";
import EmptyWorkspace from "../../components/EmptyWorkspace";

const outcomeLabel = (outcome) => ({
  MUST_FIX: "Must Fix",
  REVIEW_RECOMMENDED: "Review Recommended",
  PASSED: "Passed",
}[outcome] || "Not run");

function ValidationPage({ run, busy, onDemo, onNavigate, onProcess }) {
  const [selectedIssue, setSelectedIssue] = useState(0);
  if (!run) return <div className="page"><div className="page-heading"><span className="eyebrow">Step 4 · Quality gates</span><h1>Validation and traceability</h1><p>Every issue should say what failed, where it happened, and how to resolve it.</p></div><EmptyWorkspace title="Nothing to validate" message="Start a survey run to inspect schema, range, mapping, privacy, and transformation checks." onDemo={onDemo} onNavigate={onNavigate} busy={busy} /></div>;
  const validation = run.validation || { issues: [], counts: {} }, issues = validation.issues || [], records = run.records || [], selected = issues[selectedIssue] || issues[0], record = records.find((item) => selected && item.sourceRow === selected.sourceRow) || records[0], checksum = run.source?.checksum || run.source?.sha256;
  const summary = [[validation.counts?.passed ?? validation.validResponses ?? records.filter((item) => item.status === "valid").length, "Passed", "green"], [validation.counts?.reviewRecommended ?? validation.warnings ?? issues.filter((item) => item.severity === "warning").length, "Review Recommended", "amber"], [validation.counts?.mustFix ?? validation.errors ?? issues.filter((item) => item.severity === "error").length, "Must Fix", "red"], [run.mappings?.filter((mapping) => mapping.status === "unmapped").length || 0, "unmapped headers", "purple"]];
  return <div className="page validation-page"><div className="page-heading split-heading"><div><span className="eyebrow">Step 4 · Quality gates</span><h1>Validation and traceability</h1><p>Inspect the exact source row, question, rule version, and remediation for every finding.</p></div><button className="button primary" disabled={busy} onClick={onProcess} type="button">Run validation</button></div>
    <div className="metric-grid">{summary.map(([value, label, tone]) => <article className={`metric-card ${tone}`} key={label}><strong>{Number(value || 0).toLocaleString()}</strong><span>{label}</span></article>)}</div>
    <div className="content-grid validation-grid"><section className="card"><div className="card-heading"><div><span className="eyebrow">Actionable findings</span><h2>Issue log</h2></div><span className={`status-pill ${validation.outcome === "PASSED" ? "success" : validation.outcome === "MUST_FIX" ? "danger" : "warning"}`}>{outcomeLabel(validation.outcome)}</span></div><div className="table-scroll"><table><thead><tr><th>Outcome</th><th>Check</th><th>Message</th><th>Location</th></tr></thead><tbody>{issues.map((issue, index) => <tr className={selectedIssue === index ? "selected-row" : ""} key={issue.id || `${issue.code}-${index}`} onClick={() => setSelectedIssue(index)}><td><span className={`status-text ${issue.outcome === "MUST_FIX" ? "danger" : "warning"}`}>{outcomeLabel(issue.outcome)}</span></td><td>{String(issue.code || issue.check || "Check").replaceAll("_", " ")}</td><td>{issue.message}</td><td>{issue.location || "run"}</td></tr>)}</tbody></table>{!issues.length && <div className="success-state"><span>✓</span><strong>No validation issues found</strong><p>This run satisfies all configured export gates.</p></div>}</div></section>
      <div className="stacked-cards"><section className="card"><span className="eyebrow">Selected evidence</span><h2>Traceability preview</h2><dl className="detail-list"><div><dt>Source file</dt><dd>{run.source?.originalName || "-"}</dd></div><div><dt>Source row</dt><dd>{selected?.sourceRow || record?.sourceRow || "-"}</dd></div><div><dt>Question</dt><dd>{record?.targetQuestionCode || selected?.sourceColumn || "-"}</dd></div><div><dt>Rule version</dt><dd>{record?.ruleVersion || "-"}</dd></div><div><dt>Source checksum</dt><dd className="monospace">{checksum?.slice(0, 16) || "-"}…</dd></div></dl></section><section className="card"><span className="eyebrow">Before and after</span><h2>Record preview</h2>{record ? <><div className="comparison"><div><span>Original</span><strong>{String(record.originalValue ?? "No answer")}</strong><small>{record.originalQuestion}</small></div><span aria-hidden="true">→</span><div><span>Normalised</span><strong>{String(record.normalizedResponse ?? record.harmonisedValue ?? "-")}</strong><small>{record.targetQuestionCode}</small></div><span className={`status-pill ${record.status === "valid" ? "success" : "warning"}`}>{record.status}</span></div>{record.standardizedScore !== null && record.standardizedScore !== undefined && <p className="helper-text">Scored {record.numericScore} on the confirmed scale; 0–100 representation: <strong>{record.standardizedScore}</strong>{record.reverseApplied ? " after reverse scoring" : ""}.</p>}</> : <p className="empty-row">Run harmonisation to generate traceable records.</p>}</section></div>
    </div>
  </div>;
}
export default ValidationPage;
