import React, { useState } from "react";
import EmptyWorkspace from "../../components/EmptyWorkspace";
import { api } from "../../api";

const OUTPUTS = [["destination", "Destination-shaped CSV", "One row per source response using the selected destination's exact column order"], ["harmonised", "Long-form audit CSV", "Traceable response rows with pseudonymised identifiers and ELF metadata"], ["validation", "Validation report CSV", "Errors, warnings, locations, and recommended fixes"], ["unmapped", "Unmapped question report", "Headers still requiring human review"], ["mappings", "Mapping decisions CSV", "Reusable question-variant decisions and confidence"], ["summary", "Run summary PDF", "Counts, transformations, checksum, and quality notes"]];

function ExportPage({ run, busy, onDemo, onNavigate }) {
  const [selected, setSelected] = useState(["destination", "harmonised", "validation", "mappings", "summary"]);
  if (!run) return <div className="page"><div className="page-heading"><span className="eyebrow">Step 5 · Controlled release</span><h1>Save, resume and export outputs</h1><p>Download analysis data and its complete audit evidence.</p></div><EmptyWorkspace title="No outputs available" message="Complete a survey run before selecting export files." onDemo={onDemo} onNavigate={onNavigate} busy={busy} /></div>;
  const exportable = Boolean(run.validation?.exportable || run.stage === "exportable" || run.stage === "exported"), preview = (run.records || []).slice(0, 3), unresolved = (run.mappings || []).filter((mapping) => !["approved", "excluded"].includes(mapping.status)).length;
  const toggle = (type) => setSelected((current) => current.includes(type) ? current.filter((item) => item !== type) : [...current, type]);
  const download = () => selected.forEach((type, index) => window.setTimeout(() => { const anchor = document.createElement("a"); anchor.href = api.exportUrl(run.id, type); anchor.download = ""; document.body.appendChild(anchor); anchor.click(); anchor.remove(); }, index * 180));
  return <div className="page export-page"><div className="page-heading split-heading"><div><span className="eyebrow">Step 5 · Controlled release</span><h1>Save, resume and export outputs</h1><p>Choose the files needed for analysis, reporting, or future mapping review.</p></div><span className={`status-pill large ${exportable ? "success" : "warning"}`}>{exportable ? "Ready for export" : "Resolve blocking errors"}</span></div>
    <div className="content-grid export-grid"><section className="card output-selector"><span className="eyebrow">Export manifest</span><h2>Selectable outputs</h2><div className="output-list">{OUTPUTS.map(([type, label, description]) => <label key={type}><input type="checkbox" checked={selected.includes(type)} onChange={() => toggle(type)} /><span><strong>{label}</strong><small>{description}</small></span></label>)}</div><div className="button-row"><button className="button dark" disabled={!exportable || !selected.length} onClick={download} type="button">Download selected</button><button className="button secondary" type="button">Session saved automatically</button></div></section>
      <div className="stacked-cards"><section className="card"><span className="eyebrow">Canonical long format</span><h2>Output schema preview</h2><div className="table-scroll compact-table"><table><thead><tr><th>Person ID</th><th>Question</th><th>Value</th><th>Source</th></tr></thead><tbody>{preview.map((record, index) => <tr key={index}><td className="monospace">{record.personId?.slice(0, 10) || "-"}…</td><td>{record.targetQuestionCode}</td><td>{String(record.harmonisedValue ?? "-")}</td><td>r{record.sourceRow}</td></tr>)}</tbody></table>{!preview.length && <div className="empty-row">Run harmonisation to preview the output.</div>}</div></section><section className="card"><span className="eyebrow">Required gates</span><h2>Final checks before export</h2><div className="final-checks"><p className={exportable ? "pass" : "fail"}><span>{exportable ? "✓" : "!"}</span><strong>Critical errors resolved</strong><small>Required</small></p><p className={unresolved === 0 ? "pass" : "fail"}><span>{unresolved === 0 ? "✓" : "!"}</span><strong>Manual mappings approved</strong><small>Required</small></p><p className="pass"><span>✓</span><strong>Identifiers pseudonymised</strong><small>Required</small></p><p className={selected.length ? "pass" : "fail"}><span>{selected.length ? "✓" : "!"}</span><strong>Output options selected</strong><small>Required</small></p></div>{!exportable && <button className="button primary" onClick={() => onNavigate("validation")} type="button">Go to validation</button>}</section></div>
    </div>
  </div>;
}
export default ExportPage;
