import React from "react";

const STEPS = ["Upload", "Profile", "Map", "Transform", "Validate", "Export"];

function OverviewPage({ overview, run, onDemo, onNavigate, busy }) {
  const metrics = [[overview.datasets, "datasets available", "blue"], [overview.questionVariants, "question variants", "purple"], [overview.warnings, "active warnings", "amber"], [overview.exportable, "ready for export", "green"]];
  const mappings = run?.mappings || [];
  const reviewCount = mappings.filter((mapping) => ["review", "unmapped", "suggested"].includes(mapping.status)).length;
  const approvedPercent = mappings.length ? Math.round((mappings.filter((mapping) => ["approved", "excluded"].includes(mapping.status)).length / mappings.length) * 100) : 0;
  return <div className="page overview-page">
    <div className="page-heading split-heading"><div><span className="eyebrow">Auditable · repeatable · human controlled</span><h1>Survey harmonisation workbench</h1><p>Upload survey files, approve mappings, apply versioned rules, validate every transformation, and export traceable data.</p></div><div className="button-row"><button className="button primary" onClick={() => onNavigate("datasets")} type="button">Upload survey file</button><button className="button secondary" onClick={onDemo} disabled={busy} type="button">Load demonstration run</button></div></div>
    <div className="metric-grid">{metrics.map(([value, label, tone]) => <article className={`metric-card ${tone}`} key={label}><strong>{Number(value || 0).toLocaleString()}</strong><span>{label}</span></article>)}</div>
    <div className="content-grid two-thirds"><section className="card"><div className="card-heading"><div><span className="eyebrow">Current workflow</span><h2>{run ? `${run.metadata?.program || "Survey"} · ${run.metadata?.year || "Draft"}` : "No active run yet"}</h2></div>{run && <span className={`status-pill ${run.stage === "exportable" ? "success" : "warning"}`}>{String(run.stage || "uploaded").replaceAll("_", " ")}</span>}</div><ol className="stage-track">{STEPS.map((step, index) => <li className={run && index < 2 ? "complete" : ""} key={step}><span>{index + 1}</span><small>{step}</small></li>)}</ol>{run ? <div className="run-summary"><strong>{approvedPercent}% of question mappings resolved</strong><p>{reviewCount ? `${reviewCount} item${reviewCount === 1 ? "" : "s"} still need human review.` : "All mapping decisions are ready for deterministic processing."}</p><button className="text-button" onClick={() => onNavigate(reviewCount ? "mapping" : "validation")} type="button">Continue this run →</button></div> : <div className="run-summary muted-panel"><strong>Start with your own file or the sanitised demo.</strong><p>Original question and response values remain traceable; participant identifiers are pseudonymised.</p></div>}</section>
      <section className="card principles-card"><span className="eyebrow">Processing principles</span><h2>Automation with guardrails</h2><div className="tag-row"><span className="tag teal">Traceable</span><span className="tag purple">Configurable</span><span className="tag green">Privacy aware</span><span className="tag amber">Re-runnable</span></div><p>Exact aliases can be reused automatically. Similarity scores remain suggestions until a person confirms their meaning.</p><ul className="check-list"><li>Original questions and values retained in the audit trail</li><li>Typed rules only, no user-entered code execution</li><li>Blocking validation errors stop export</li></ul></section></div>
  </div>;
}
export default OverviewPage;
